version: '3.3'

services:
        app:
                container_name: orderservice_v1
                build:
                        context: .
                        dockerfile: Dockerfile
                restart: always
                ports:
                        - "54421:54421"
